[package]
name = "bucket_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aligners = "0.0.10"
bumpalo = { version = "3.14.0", features = ["collections", "allocator-api2"]}
hashbrown = "0.14.2"
memmap2 = "0.9.0"
page_size = "0.6.0"
itertools = "0.12.0"
bytemuck = { version = "1.14.0", features = ["derive"] }
size = "0.4.1"
either = "1.8.1"
getset = "0.1.2"
once_cell = "1.18.0"
fnv_rs = "0.4.3"
