[package]
name = "bbolt-rs"
version = "1.38.0"
edition = "2021"
license-file = "LICENSE"
categories = ["command-line-utilities", "database-implementations"]
keywords = ["cli", "bbolt", "database", "db"]
rust-version = "1.76"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aligners = "0.0.10"
bumpalo = { version = "3.14", features = ["collections", "allocator-api2"]}
hashbrown = "0.14.3"
memmap2 = "0.9.4"
page_size = "0.6.0"
itertools = "0.12.1"
bytemuck = { version = "1.14", features = ["derive"] }
size = "0.4.1"
either = "1.9.0"
getset = "0.1.2"
once_cell = "1.19.0"
fnv_rs = "0.4.3"
thiserror = "1.0.56"
anyhow = "1.0.79"
fs4 = { version = "0.7.0", features = ["sync"] }
parking_lot = "0.12.1"
aliasable = "0.1.3"
pin-project = "1.1.4"
typed-builder = "0.18.1"

[dev-dependencies]
tempfile = "3.10"

[build-dependencies]
cfg_aliases = "0.2.0"

[profile.release]
debug = true

[profile.bench]
debug = true