[package]
name = "bbolt-rs"
version = "0.138.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aligners = "0.0.10"
bumpalo = { version = "3.14.0", features = ["collections", "allocator-api2"]}
hashbrown = "0.14.3"
memmap2 = "0.9.2"
page_size = "0.6.0"
itertools = "0.12.0"
bytemuck = { version = "1.14.0", features = ["derive"] }
size = "0.4.1"
either = "1.9.0"
getset = "0.1.2"
once_cell = "1.19.0"
fnv_rs = "0.4.3"
thiserror = "1.0.51"
anyhow = "1.0.75"
fs4 = { version = "0.7.0", features = ["sync"] }
parking_lot = "0.12.1"
